import type { CSSProperties } from "react";

/** Shared inline-style tokens for the /admin panel — plain and functional, not the storefront theme. */
export const adminStyles = {
  page: { padding: "28px 24px 60px", maxWidth: 1100, margin: "0 auto" } as CSSProperties,
  h1: { margin: "0 0 20px", fontSize: 24, fontWeight: 800 } as CSSProperties,
  card: {
    background: "#fff",
    border: "2px solid #2E1A10",
    borderRadius: 16,
    padding: 22,
    boxShadow: "4px 4px 0 #2E1A10",
  } as CSSProperties,
  label: { display: "block", fontSize: 12.5, fontWeight: 700, margin: "0 0 6px" } as CSSProperties,
  input: {
    width: "100%",
    padding: 10,
    border: "2px solid #2E1A10",
    borderRadius: 10,
    fontSize: 14,
    marginBottom: 16,
    fontFamily: "inherit",
    background: "#fff",
    color: "#2E1A10",
  } as CSSProperties,
  row: { display: "flex", gap: 16, flexWrap: "wrap" } as CSSProperties,
  col: { flex: "1 1 220px", minWidth: 0 } as CSSProperties,
  button: {
    padding: "11px 18px",
    border: "2px solid #2E1A10",
    borderRadius: 12,
    background: "#EE6A26",
    color: "#fff",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    boxShadow: "3px 3px 0 #2E1A10",
  } as CSSProperties,
  buttonGhost: {
    padding: "10px 16px",
    border: "2px solid #2E1A10",
    borderRadius: 12,
    background: "#fff",
    color: "#2E1A10",
    fontWeight: 700,
    fontSize: 13.5,
    cursor: "pointer",
  } as CSSProperties,
  buttonDanger: {
    padding: "10px 16px",
    border: "2px solid #C9490F",
    borderRadius: 12,
    background: "#FFE7D6",
    color: "#C9490F",
    fontWeight: 700,
    fontSize: 13.5,
    cursor: "pointer",
  } as CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13.5 } as CSSProperties,
  th: {
    textAlign: "left",
    padding: "9px 10px",
    borderBottom: "2px solid #2E1A10",
    fontSize: 11.5,
    textTransform: "uppercase",
    letterSpacing: ".4px",
    color: "#8A7263",
  } as CSSProperties,
  td: { padding: "9px 10px", borderBottom: "1px solid #EFE6DE" } as CSSProperties,
};
